### ISSUE TITLE
readme

### ISSUE THREAD

**Issue by pfefferle** [indieweb/wordpress-indieweb-press-this#11]
@dshanske @chrisaldrich @miklb can you please help with the readme file, so I can upload it to the WP.org repo.

**Comment by miklb** [comment]
Absolutely!

**Comment by miklb** [comment]
@pfefferle @dshanske  Just double checking, is license implied or do the plugins need to explicitly be set?

**Comment by pfefferle** [comment]
we have to make it explicit. @snarfed should we start with MIT or can we use CC0?

**Comment by snarfed** [comment]
i licensed the original bookmarklets as public domain, but feel free to use any license you want for this plugin! i don't have an opinion.
