### ISSUE TITLE
New Filters

### ISSUE THREAD

**Issue by pfefferle** [indieweb/wordpress-indieweb-press-this#5]
Perhaps we can also use some of the newly introduced (WP 4.2) Filters:
- https://developer.wordpress.org/reference/hooks/press_this_data/
- https://developer.wordpress.org/reference/hooks/press_this_suggested_html/
- https://developer.wordpress.org/reference/hooks/press_this_save_redirect/

and
- https://developer.wordpress.org/reference/hooks/enable_press_this_media_discovery/

**Comment by snarfed** [comment]
ooh, those look great! way better than the JavaScript right now. go for it! (and thanks for the fixes!)
